name: Android Build and Ktlint Check

on:
  pull_request:
    branches: [ main ]

jobs:
  ktlint_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 17

    - name: Run ktlint
      run: |
        cd android-example
        ./gradlew ktlint
