name: Android Build and Ktlint Check

on:
  pull_request:
    branches: [ main ]

jobs:
  ktlint_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run ktlint
      run: |
        cd android-example
        ./gradlew ktlint
