name: Test github actions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google_play_scraper

    - name: Get version from Google Play
      id: get_version
      run: |
        echo "VERSION=$(python scripts/get_version_from_store.py $APPLICATION_ID)" >> $GITHUB_ENV
      env:
        APPLICATION_ID: ${{ vars.APPLICATION_ID }}

    - name: show extracted the version
      run: |
        echo "Detected version: $VERSION"

    - name: Merge release PR
      run: |
        PRs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Accept: application/vnd.github.v3+json" \
                   "https://api.github.com/repos/${{ github.repository }}/pulls")
        echo "$PRs"
        for PR in $(echo "$PRs" | jq -r '.[] | select( .head | .ref | test("^release/v[0-9]+\\.[0-9]+\\.[0-9]+$")) | .number'); do
          echo "match: PR #$PR"
          curl -s -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/$PR/merge"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
