name: Test github actions

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google_play_scraper

    - name: Get version from Google Play
      id: get_version
      run: |
        echo "VERSION=$(python scripts/get_version_from_store.py $APPLICATION_ID)" >> $GITHUB_ENV
      env:
        APPLICATION_ID: ${{ vars.APPLICATION_ID }}

    - name: show extracted the version
      run: |
        echo "Detected version: $VERSION"

    - name: Auto merge PR
      uses: pascalgn/automerge-action@v0.15.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
