name: Experiment GitHub Actions

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      ext1: ${{ steps.set_output.outputs.ext1 }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: show and update value
      id: set_output
      run: |
        echo "ext1=$(date)" >> $GITHUB_OUTPUT
        echo ${{ steps.set_output.outputs.ext1 }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    env:
      ext1: ${{ needs.job1.outputs.ext1 }}
    outputs:
      ext2: ${{ steps.set_output.outputs.ext2 }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: show value
      id: set_output
      run: |
        echo "$ext1"
        echo "ext2=$ext1" >> $GITHUB_OUTPUT

  job3:
    needs: job2
    runs-on: ubuntu-latest
    env:
      ext1: ${{ needs.job1.outputs.ext1 }}
      ext2: ${{ needs.job2.outputs.ext2 }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: show value
      run: |
        echo "$ext1"
        echo "$ext2"


